version: '3.8'

services:

# Redis
    redis:
        image: redis:3.2.8
        hostname: redis
        ports:
          - "6379:6379"

# RabbitMQ
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3-management
        env_file:
            - .env.dev
        ports:
            - "5672:5672"
            - "15672:15672"

# Celery worker
    worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./run_celery.sh
        volumes:
            - .:/code:Z
        env_file:
            - .env.dev
        links:
            # - db
            - rabbitmq
            - redis
        depends_on:
            - rabbitmq


  # Django
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./run_web.sh
        volumes:
            - .:/code:Z
        ports:
            - "8001:8000"
        env_file:
            - .env.dev
        links:
            # - db
            - rabbitmq
            - redis
        # depends_on:
        #     - db
    web2:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./run_web.sh
        volumes:
            - .:/code:Z
        ports:
            - "8002:8000"
        env_file:
            - .env.dev
        links:
            # - db
            - rabbitmq
            - redis
        # depends_on:
        #     - db
    db:
        image: postgres:15
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

     # Nginx Load Balancer
    nginx:
        image: nginx:latest
        ports:
        - "80:80"
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
        - web2
        - web

volumes:
  postgres_data:

