name: Linters

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort

      - name: Run Black
        run: black . --check

      - name: Run Flake8
        run: flake8 .

      - name: Run isort
        run: isort . --check-only --diff
